export default function DocumentsPage() {
  return (
    <div style={{ padding: "32px 32px", minHeight: "100vh" }}>
      {/* Header */}
      <div style={{ marginBottom: 24 }}>
        <h1 style={{ fontSize: 22, fontWeight: 700, color: "#fff", margin: 0, marginBottom: 4 }}>Documents</h1>
        <p style={{ fontSize: 13, color: "#6b7280", margin: 0 }}>Files generated by Wally or other agents</p>
      </div>

      {/* Empty State */}
      <div
        style={{
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
          padding: "80px 32px",
          background: "#161616",
          border: "1px solid #222",
          borderRadius: 12,
          textAlign: "center",
        }}
      >
        <div style={{ fontSize: 36, marginBottom: 16, opacity: 0.4 }}>📄</div>
        <div style={{ fontSize: 14, fontWeight: 600, color: "#6b7280", marginBottom: 8 }}>No documents yet</div>
        <div style={{ fontSize: 13, color: "#374151", maxWidth: 360, lineHeight: 1.6 }}>
          Documents generated by Wally or other agents will appear here.
        </div>
      </div>
    </div>
  );
}
